// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/OutcomeFirstVariant.tsx": () => import("../components/mockups/OutcomeFirstVariant.tsx"),
  "./components/mockups/ProblemFirstVariant.tsx": () => import("../components/mockups/ProblemFirstVariant.tsx"),
  "./components/mockups/TrustFirstVariant.tsx": () => import("../components/mockups/TrustFirstVariant.tsx")
};
