-- Phase 1.7 / 1.8 — transactional ledger writes, order-number sequences,
-- and coupon usage limits.
--
-- Safe to re-run.

-- ===========================================================================
-- 1. ORDER NUMBER SEQUENCES
-- ---------------------------------------------------------------------------
-- Order numbers were generated by counting existing rows and adding one:
--   const { count } = await supabase.from('reseller_orders').select(...)
--   const baseSerial = (count || 0) + 10001
-- Two concurrent checkouts read the same count and mint the same number. A
-- sequence is atomic and never reuses a value, even on rollback.
-- ===========================================================================

CREATE SEQUENCE IF NOT EXISTS reseller_order_serial START WITH 10001;
CREATE SEQUENCE IF NOT EXISTS formal_order_serial   START WITH 1;

-- Seed past whatever already exists so we never collide with historic numbers.
SELECT setval(
  'reseller_order_serial',
  GREATEST((SELECT COUNT(*) FROM reseller_orders) + 10001, 10001),
  false
);

CREATE OR REPLACE FUNCTION next_reseller_order_number()
RETURNS TEXT LANGUAGE sql AS $$
  SELECT 'RSL-SF-' || nextval('reseller_order_serial')::text;
$$;

-- ===========================================================================
-- 2. COUPON USAGE LIMITS
-- ---------------------------------------------------------------------------
-- Checkout validated only is_active and expires_at, so a code could be reused
-- without limit, by anyone, on any order size.
-- ===========================================================================

ALTER TABLE reseller_storefront_coupons
  ADD COLUMN IF NOT EXISTS max_redemptions      INTEGER,          -- NULL = unlimited
  ADD COLUMN IF NOT EXISTS times_redeemed       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_per_customer     INTEGER,          -- NULL = unlimited
  ADD COLUMN IF NOT EXISTS min_order_value_paise BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS reseller_coupon_redemptions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id     UUID NOT NULL REFERENCES reseller_storefront_coupons(id) ON DELETE CASCADE,
  customer_id   UUID REFERENCES reseller_storefront_customers(id) ON DELETE SET NULL,
  guest_phone   TEXT,
  order_number  TEXT,
  redeemed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_coupon
  ON reseller_coupon_redemptions (coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_customer
  ON reseller_coupon_redemptions (coupon_id, customer_id);

/**
 * Atomically claim one redemption of a coupon.
 * Returns the coupon row when the claim succeeds, or no rows when a limit is
 * hit. The UPDATE ... WHERE times_redeemed < max_redemptions is what makes the
 * global cap race-free: concurrent callers serialise on the row lock and the
 * loser's predicate fails.
 */
CREATE OR REPLACE FUNCTION claim_coupon(
  p_reseller_id     UUID,
  p_code            TEXT,
  p_customer_id     UUID,
  p_guest_phone     TEXT,
  p_order_value_paise BIGINT
)
RETURNS TABLE (discount_type TEXT, discount_value NUMERIC)
LANGUAGE plpgsql AS $$
DECLARE
  v_coupon reseller_storefront_coupons%ROWTYPE;
  v_used_by_customer INTEGER;
BEGIN
  SELECT * INTO v_coupon
  FROM reseller_storefront_coupons
  WHERE reseller_id = p_reseller_id
    AND upper(code) = upper(p_code)
    AND is_active
  FOR UPDATE;

  IF NOT FOUND THEN RETURN; END IF;
  IF v_coupon.expires_at IS NOT NULL AND v_coupon.expires_at <= NOW() THEN RETURN; END IF;
  IF p_order_value_paise < v_coupon.min_order_value_paise THEN RETURN; END IF;
  IF v_coupon.max_redemptions IS NOT NULL
     AND v_coupon.times_redeemed >= v_coupon.max_redemptions THEN RETURN; END IF;

  IF v_coupon.max_per_customer IS NOT NULL THEN
    SELECT COUNT(*) INTO v_used_by_customer
    FROM reseller_coupon_redemptions r
    WHERE r.coupon_id = v_coupon.id
      AND ( (p_customer_id IS NOT NULL AND r.customer_id = p_customer_id)
         OR (p_customer_id IS NULL AND p_guest_phone IS NOT NULL AND r.guest_phone = p_guest_phone) );
    IF v_used_by_customer >= v_coupon.max_per_customer THEN RETURN; END IF;
  END IF;

  UPDATE reseller_storefront_coupons
     SET times_redeemed = times_redeemed + 1
   WHERE id = v_coupon.id;

  INSERT INTO reseller_coupon_redemptions (coupon_id, customer_id, guest_phone)
  VALUES (v_coupon.id, p_customer_id, p_guest_phone);

  discount_type  := v_coupon.discount_type;
  discount_value := v_coupon.discount_value;
  RETURN NEXT;
END;
$$;

-- ===========================================================================
-- 3. ATOMIC FIFO ISSUANCE
-- ---------------------------------------------------------------------------
-- lib/fifoEngine.executeFifoPlan looped in Node: insert a lot_issuance, then
-- rpc decrement_lot_qty, per reservation, throwing on failure. A mid-loop
-- error left lots partially consumed with no rollback. The plan was also never
-- re-validated at execution, so two concurrent orders could both reserve the
-- same stock and drive remaining_qty negative.
--
-- This does the whole plan in one transaction, locks each lot, and re-checks
-- availability before consuming.
-- ===========================================================================

CREATE OR REPLACE FUNCTION execute_fifo_plan(
  p_reservations JSONB,   -- [{lot_id, issued_qty, unit_cost, total_cost}, ...]
  p_mfg_order_id UUID,
  p_issuance_type TEXT,   -- 'reserved' | 'final'
  p_created_by   TEXT
)
RETURNS TABLE (total_cost NUMERIC)
LANGUAGE plpgsql AS $$
DECLARE
  r           JSONB;
  v_lot_id    UUID;
  v_qty       NUMERIC;
  v_remaining NUMERIC;
  v_total     NUMERIC := 0;
BEGIN
  IF p_issuance_type NOT IN ('reserved', 'final') THEN
    RAISE EXCEPTION 'Invalid issuance_type: %', p_issuance_type;
  END IF;

  FOR r IN SELECT * FROM jsonb_array_elements(p_reservations)
  LOOP
    v_lot_id := (r->>'lot_id')::UUID;
    v_qty    := (r->>'issued_qty')::NUMERIC;

    IF v_qty <= 0 THEN CONTINUE; END IF;

    -- Lock the lot and re-read availability inside the transaction.
    SELECT remaining_qty INTO v_remaining
    FROM purchase_lots WHERE id = v_lot_id FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Purchase lot % not found', v_lot_id;
    END IF;
    IF v_remaining < v_qty THEN
      RAISE EXCEPTION
        'Lot % has only % remaining but % was planned — stock changed since the plan was computed',
        v_lot_id, v_remaining, v_qty;
    END IF;

    INSERT INTO lot_issuances (
      lot_id, manufacturing_order_id, issued_qty, unit_cost, total_cost,
      issuance_type, finalised_at, created_by
    ) VALUES (
      v_lot_id, p_mfg_order_id, v_qty,
      (r->>'unit_cost')::NUMERIC, (r->>'total_cost')::NUMERIC,
      p_issuance_type,
      CASE WHEN p_issuance_type = 'final' THEN NOW() ELSE NULL END,
      p_created_by
    );

    UPDATE purchase_lots
       SET remaining_qty = remaining_qty - v_qty,
           status = CASE WHEN remaining_qty - v_qty <= 0 THEN 'depleted' ELSE status END
     WHERE id = v_lot_id;

    v_total := v_total + (r->>'total_cost')::NUMERIC;
  END LOOP;

  total_cost := v_total;
  RETURN NEXT;
END;
$$;

-- ===========================================================================
-- 4. ATOMIC REPLENISHMENT OFFSET
-- ---------------------------------------------------------------------------
-- lib/replenishmentEngine.executeReplenishmentOffset did insert → select →
-- update per obligation with no transaction and no lock, so two concurrent
-- gold purchases could both read the same remaining_qty_g and offset the same
-- obligation twice.
-- ===========================================================================

CREATE OR REPLACE FUNCTION execute_replenishment_offset(
  p_offsets        JSONB,  -- [{obligation_id, qty_offset, obligation_rate, purchase_rate, delta}, ...]
  p_purchase_lot_id UUID
)
RETURNS TABLE (total_delta NUMERIC)
LANGUAGE plpgsql AS $$
DECLARE
  o             JSONB;
  v_ob_id       UUID;
  v_qty         NUMERIC;
  v_remaining   NUMERIC;
  v_new_remain  NUMERIC;
  v_total       NUMERIC := 0;
BEGIN
  FOR o IN SELECT * FROM jsonb_array_elements(p_offsets)
  LOOP
    v_ob_id := (o->>'obligation_id')::UUID;
    v_qty   := (o->>'qty_offset')::NUMERIC;

    IF v_qty <= 0 THEN CONTINUE; END IF;

    SELECT remaining_qty_g INTO v_remaining
    FROM replenishment_obligations WHERE id = v_ob_id FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Replenishment obligation % not found', v_ob_id;
    END IF;

    -- Another purchase may have offset this obligation since the preview was
    -- computed. Clamp rather than driving the balance negative.
    IF v_remaining < v_qty THEN
      v_qty := v_remaining;
    END IF;
    IF v_qty <= 0 THEN CONTINUE; END IF;

    INSERT INTO replenishment_offsets (
      obligation_id, purchase_lot_id, qty_offset_g,
      obligation_rate, purchase_rate, delta, offset_date
    ) VALUES (
      v_ob_id, p_purchase_lot_id, v_qty,
      (o->>'obligation_rate')::NUMERIC,
      (o->>'purchase_rate')::NUMERIC,
      -- Recompute from the clamped qty so the delta matches what was applied.
      ROUND(v_qty * ((o->>'purchase_rate')::NUMERIC - (o->>'obligation_rate')::NUMERIC), 2),
      CURRENT_DATE
    );

    v_new_remain := ROUND(v_remaining - v_qty, 4);

    UPDATE replenishment_obligations
       SET remaining_qty_g = v_new_remain,
           status = CASE WHEN v_new_remain <= 0 THEN 'fully_offset' ELSE 'partially_offset' END
     WHERE id = v_ob_id;

    v_total := v_total + ROUND(v_qty * ((o->>'purchase_rate')::NUMERIC - (o->>'obligation_rate')::NUMERIC), 2);
  END LOOP;

  total_delta := v_total;
  RETURN NEXT;
END;
$$;
